### ISSUE TITLE
ERROR    websocket         error from callback <bound method Client.on_close of <gardena.smart_system.Client object at 0x600239b0>>: (invalid_grant) Failed to find token

### ISSUE THREAD

**Issue by Pol3cat** [py-smart-gardena/py-smart-gardena#20]
Hi again,
seams i got the similar error again (from 7.June):
`ERROR    websocket         error from callback <bound method Client.on_close of <gardena.smart_system.Client object at 0x600239b0>>: (invalid_grant) Failed to find token
`
i got this error at 6:38 before i open the websocket again.
I open the socket every day at 7:00 and close it at 22:00 because
I usually want to keep the connection alive every time but somedays the status seams to be frozen.
I have to reconnect and everything works fine until some days.

To disconnect the websocket is there a special command to exit the websocket.
At the moment i disconnect via "break" i the while loop

Here my complete pyhton code..

```
#!/usr/bin/env python3
# gardena_garten_system.py


# SmartSystem need : 
# https://github.com/py-smart-gardena/py-smart-gardena
# https://developer.husqvarnagroup.cloud/docs/getting-started#/docs/getting-started/#3connect-api-to-application

from gardena.smart_system import SmartSystem
from datetime import datetime
from requests import HTTPError
import pprint
import pytest
import unittest
import requests
import requests_mock
import time
import sys

    

LOCATION_ID = "xxx"  #nicht ändern!

sh.Gardena.OnOff(1) #Setze beim Auslösen den Schalter auf Eins



smart_system = SmartSystem(email="xxx", password="xxx", client_id="xxx") # ID aus API nehmen und anpassen. Letzte Änderung der ID am 18.7.2020
smart_system.authenticate()
smart_system.update_locations()



for location in smart_system.locations.values():
    smart_system.update_devices(location)
    pprint.pprint(location)
    for device in location.devices.values():
        pprint.pprint(device)

smart_system.start_ws(smart_system.locations[LOCATION_ID])        

sh.Gardena.mower.status('Warte auf Start...')
sh.Gardena.mower.battery_state("Warte auf Start...") 


while sh.Gardena.OnOff:
    tageszeit = sh.now()
    if (tageszeit.hour >= 20) and (tageszeit.hour < 23):
        sh.Gardena.OnOff(0)
        break
    if (tageszeit.hour >= 12) and (tageszeit.hour < 13):
        sh.Gardena.OnOff(0)
        break
    if (tageszeit.hour >= 7) and (tageszeit.hour < 20):
        for device in smart_system.locations[LOCATION_ID].find_device_by_type("MOWER"):
            sh.Gardena.mower.battery(device.battery_level)
            sh.Gardena.mower.radio_quality(device.rf_link_level)    

            if (device.battery_level < 5):
                sh.telegram.photo_broadcast('https://icon-icons.com/icons2/2248/PNG/96/robot_mower_icon_136263.png', 'Batterie kritisch: %d '% device.battery_level, 832868784)
                #Schalte Tunnel öffnen
                requests.get('http://192.168.178.56/control?cmd=gpio,14,0')     
                
            if device.activity == 'PARKED_PARK_SELECTED':
                sh.Gardena.mower.status('Geparkt')
            elif device.activity == 'OK_CUTTING_TIMER_OVERRIDDEN':
                sh.Gardena.mower.status('Manuelles Mähen')
                #Schalte Tunnel schliessen
                requests.get('http://192.168.178.56/control?cmd=gpio,14,1')
            elif device.activity == 'OK_SEARCHING':
                sh.Gardena.mower.status('Suche Ladestation')
                #Schalte Tunnel öffnen
                requests.get('http://192.168.178.56/control?cmd=gpio,14,0')
            elif device.activity == 'OK_CUTTING':
                sh.Gardena.mower.status('Am Mähen')
                #Schalte Tunnel schliessen
                requests.get('http://192.168.178.56/control?cmd=gpio,14,1')
            elif device.activity == 'OK_LEAVING':
                sh.Gardena.mower.status('Fahre zur Startposition')
                sh.Gardena.mower.in_charge(0)
                #Schalte Tunnel öffnen
                requests.get('http://192.168.178.56/control?cmd=gpio,14,0')
            elif device.activity == 'OK_CHARGING':
                sh.Gardena.mower.status('Am Laden')
                sh.Gardena.mower.in_charge(1)
                #Schalte Tunnel öffnen
                requests.get('http://192.168.178.56/control?cmd=gpio,14,0')
            elif device.activity == 'PARKED_TIMER':
                sh.Gardena.mower.status('Geparkt bis Timer')
                #Schalte Tunnel öffnen
                requests.get('http://192.168.178.56/control?cmd=gpio,14,0')
            elif device.activity == 'PARKED_AUTOTIMER':
                sh.Gardena.mower.status('Geparkt bis Timer - Grashöhe unzureichend')
                #Schalte Tunnel öffnen
                requests.get('http://192.168.178.56/control?cmd=gpio,14,0')
            elif device.activity == 'PAUSED':
               sh.Gardena.mower.status('Angehalten')
            elif device.activity == 'NONE':                
                if device.last_error_code == 'OFF_HATCH_OPEN':                
                    sh.Gardena.mower.status('Klappe geöffnet')               
            else:
                sh.Gardena.mower.status(device.activity)

            if (sh.Gardena.mower.last_status() != sh.Gardena.mower.status()):
                logger.warning('Mäher: Neuer Status : %s' % sh.Gardena.mower.status())
                sh.telegram.photo_broadcast('https://icon-icons.com/icons2/2248/PNG/96/robot_mower_icon_136263.png', 'Neuer Status : %s' % sh.Gardena.mower.status(), 832868784)
                sh.Gardena.mower.last_status(sh.Gardena.mower.status())        
            
           
                
            
            if device.battery_state == 'OK':
                sh.Gardena.mower.battery_state("Alles OK")
            elif device.battery_state == 'LOW':
                sh.Gardena.mower.battery_state("Niedrig")
            elif device.battery_state == 'REPLACE_NOW':    
                sh.Gardena.mower.battery_state("Batterie bitte ersetzen")
            elif device.battery_state == 'OUT_OF_OPERATION':    
                sh.Gardena.mower.battery_state("Batterie muss ersetzt werden")
            elif device.battery_state == 'CHARGING':    
                sh.Gardena.mower.battery_state("Am Laden")
            elif device.battery_state == 'NO_BATTERY':
                sh.Gardena.mower.battery_state("Keine Batterie")
            else:
                sh.Gardena.mower.battery_state("unbekannt")   


sh.Gardena.Update_Date(tageszeit)            
    time.sleep(5)
    
      

        
sh.Gardena.mower.status('Offline')
sh.Gardena.mower.battery(0)
sh.Gardena.mower.battery_state("Offline") 
sh.Gardena.mower.radio_quality(0)   
sh.Gardena.mower.in_charge(0)
sh.Gardena.mower.last_status("Offline")
`
```

**Comment by grm** [comment]
Hello,

I am not sure to understand your issue. Do you always have thee issue ? Or the issue appears one time ?

Jérémie

**Comment by Pol3cat** [comment]
hi Jérémie,
at the moment i didn't get any error. Very strange.
Yesterday my limit exceeded, so i generate a new api key (this is every month) but the main error did not appears. strange!

**Comment by grm** [comment]
What do you mean by API key ? a key from the developer portal ?

Strange i never noticed i had to restart my domotic system (but I restart home assistant pretty often, so myabe i did not have a look into it.

**Comment by Pol3cat** [comment]
Yes from the portal.

i restart every day the connection to the gardena plugin.

In the morning i start it and in the evening i stop it. i have serveral disconnections when i turn it the whole day on.

**Comment by grm** [comment]
i never had to recreate an application key from the gardena portal.
Did you tried to contact the dev ? 
If not, i can try to contact them but i will ask you for application id and credentials.

**Comment by Pol3cat** [comment]
mhh strange.
Every month the same.:
i got following error:
2020-09-25  00:19:00 ERROR    websocket         error from callback <bound method Client.on_close of <gardena.smart_system.Client object at 0x646b7910>>: 429 Client Error:  for url: https://api.smart.gardena.dev/v1/websocket
2020-09-25  00:19:00 ERROR    websocket         error from callback <bound method Client.on_close of <gardena.smart_system.Client object at 0x730a3250>>: 429 Client Error:  for url: https://api.smart.gardena.dev/v1/websocket
2020-09-25  00:19:00 ERROR    websocket         error from callback <bound method Client.on_close of <gardena.smart_system.Client object at 0x64642b70>>: 429 Client Error:  for url: https://api.smart.gardena.dev/v1/websocket
2020-09-25  00:19:00 ERROR    websocket         error from callback <bound method Client.on_close of <gardena.smart_system.Client object at 0x65a3ea50>>: 429 Client Error:  for url: https://api.smart.gardena.dev/v1/websocket
2020-09-25  00:19:00 ERROR    websocket         error from callback <bound method Client.on_close of <gardena.smart_system.Client object at 0x60080130>>: 429 Client Error:  for url: https://api.smart.gardena.dev/v1/websocket
2020-09-25  00:19:00 ERROR    websocket         error from callback <bound method Client.on_close of <gardena.smart_system.Client object at 0x605c5f30>>: 429 Client Error:  for url: https://api.smart.gardena.dev/v1/websocket
2020-09-25  00:19:00 ERROR    websocket         error from callback <bound method Client.on_close of <gardena.smart_system.Client object at 0x60456690>>: 429 Client Error:  for url: https://api.smart.gardena.dev/v1/websocket
2020-09-25  00:19:00 ERROR    websocket         error from callback <bound method Client.on_close of <gardena.smart_system.Client object at 0x730af770>>: 429 Client Error:  for url: https://api.smart.gardena.dev/v1/websocket
2020-09-25  00:19:00 ERROR    websocket         error from callback <bound method Client.on_close of <gardena.smart_system.Client object at 0x657f1750>>: 429 Client Error:  for url: https://api.smart.gardena.dev/v1/websocket
2020-09-25  00:19:00 ERROR    websocket         error from callback <bound method Client.on_close of <gardena.smart_system.Client object at 0x658229d0>>: 429 Client Error:  for url: https://api.smart.gardena.dev/v1/websocket
2020-09-25  00:19:00 ERROR    websocket         error from callback <bound method Client.on_close of <gardena.smart_system.Client object at 0x600143d0>>: 429 Client Error:  for url: https://api.smart.gardena.dev/v1/websocket
2020-09-25  00:19:00 ERROR    websocket         error from callback <bound method Client.on_close of <gardena.smart_system.Client object at 0x64698350>>: 429 Client Error:  for url: https://api.smart.gardena.dev/v1/websocket
2020-09-25  00:19:00 ERROR    websocket         error from callback <bound method Client.on_close of <gardena.smart_system.Client object at 0x65805850>>: 429 Client Error:  for url: https://api.smart.gardena.dev/v1/websocket
2020-09-25  00:19:00 ERROR    websocket         error from callback <bound method Client.on_close of <gardena.smart_system.Client object at 0x65a3e4b0>>: 429 Client Error:  for url: https://api.smart.gardena.dev/v1/websocket
2020-09-25  07:21:37 ERROR    gardena.smart_system 429 : Limit Exceeded


maybe my source is not the best and so the websocket don't work good enough. only 30000request a month are allowed.
i will now let my connection alive the whole day. maybe it works better. hope the source or websocket will reconnect after a lost connection

**Comment by Pol3cat** [comment]
At the moment a have no errors. now i start the plugin only one time at system startup and it refresh the status every second. seams that will work...

did the plugin have a feature to control the mower? e.g. turn it into move home, start mowing?!

**Comment by grm** [comment]
Yes it does :)

**Comment by Pol3cat** [comment]
oh really, keep me in suspense! ;)

**Comment by grm** [comment]
Hey hey,

you have 4 methods on the mower device : 

sh.Gardena.mower.start_seconds_to_override(duration): starts manually the mower x seconds, overriding the schedule. duration MUST be positive multiple of 60.
sh.Gardena.mower.start_dont_override(duration) : Sets the mower in automatice mode. I think duration is not used but must be defined.
sh.Gardena.mower.park_until_next_task() : Park the mower until next scheduled task
sh.Gardena.mower.park_until_further_notice() : Park the mower and don't restart until manueally restarted

Jérémie

**Comment by Pol3cat** [comment]
oh thx. really nice.
may i can force start my mower when it runs out of the field. ;)

**Comment by grm** [comment]
Force start when it runs out of the field ? Sorry i did not get it.

**Comment by Pol3cat** [comment]
i have passage with a relay that closes the passage. sometimes the mower stopped in passage and i got the error " out of field". maybe so i can open the passage and force a start command.

**Comment by grm** [comment]
I ma not sure about your use case ! As the mower is in error, I am not sure
you will be able to retart it. You should give it a try.

And it would be great to have your feedback ;)

**Comment by Pol3cat** [comment]
i only get the error in the gardena app not via the api. maybe it will work. 

i will try and give you a feedback

**Comment by grm** [comment]
Hello @Pol3cat 

Do you have some feedback for us ? ;)

Thanks,
Jérémie

**Comment by stromnet** [comment]
Got the same now, when I did a venv reinstall of my project (due to new python interpretter).

This seems to be caused by websocket-client 0.58.0 being installed, rather than 0.57.0 that is explicitly depended on by this project. In 0.58.0 they broke the callback scheme: https://github.com/websocket-client/websocket-client/issues/669

But, not really sure why it installs the newer one.. The only dependency besides py-smart-gardena in my requirements.txt is prometheus-client..

```
$ ./venv/bin/pip3 install -r requirements.txt
Collecting py-smart-gardena
  Using cached py_smart_gardena-0.7.10-py3-none-any.whl
Collecting prometheus-client
  Using cached prometheus_client-0.10.1-py2.py3-none-any.whl (55 kB)
Collecting requests
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting oauthlib
  Using cached oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)
Collecting websocket-client
  Using cached websocket_client-0.58.0-py2.py3-none-any.whl (61 kB)
Collecting requests-oauthlib
  Using cached requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: urllib3, idna, chardet, certifi, six, requests, oauthlib, websocket-client, requests-oauthlib, py-smart-gardena, prometheus-client
Successfully installed certifi-2020.12.5 chardet-4.0.0 idna-2.10 oauthlib-3.1.0 prometheus-client-0.10.1 py-smart-gardena-0.7.10 requests-2.25.1 requests-oauthlib-1.3.0 six-1.15.0 urllib3-1.26.4 websocket-client-0.58.0
```

By bumping to websocket-client 0.58.0, together with adding "ws" obj, it works again (also in this diff, unrelated reconnect stuff.. keeping it here in case maintainer thinks it might be useful. not sure why I added that last season.. did it crash if first reconnect failed? or just looped? cannot remember!)

```
@@ -23,25 +25,32 @@ class Client:
         self.location = location
         self.should_stop = False

-    def on_message(self, message):
+    def on_message(self, ws, message):
         self.smart_system.on_message(message)

-    def on_error(self, error):
+    def on_error(self, ws, error):
         self.logger.error(f"error : {error}")
         self.smart_system.set_ws_status(False)

     def is_connected(self):
         return self.live

-    def on_close(self):
+    def on_close(self, ws):
         self.live = False
         self.logger.info("Connection close to gardena API")
         self.smart_system.set_ws_status(False)
         if not self.should_stop:
             self.logger.info("Restarting websocket")
-            self.smart_system.start_ws(self.location)
+            try:
+                self.smart_system.start_ws(self.location)
+            except RequestException as e:
+                self.logger.exception("Failed to auto-reconnect, retrying in 10s")
+                time.sleep(10)
+
+        self.logger.info("Websocket succesfully reconnected")
+

-    def on_open(self):
+    def on_open(self, ws):
```
