### ISSUE TITLE
Package install fails with python 3.12.1

### ISSUE THREAD

**Issue by ReneNulschDE** [py-smart-gardena/py-smart-gardena#228]
Trying to use this package with python=3.12.1. Installation with pip fails with the exception below.

Looks like the used python-versioneer (/versioneer.py) script is outdated.

A potential quick hack before open pandora's box of build pipeline: lines [342-344](https://github.com/py-smart-gardena/py-smart-gardena/blob/8de91ebcfbc58c4335517540d045d9f359dc95f2/versioneer.py#L342). SafeConfigParser is deprecated since Python=3.2.

Replace:
```
    parser = configparser.SafeConfigParser()
    with open(setup_cfg, "r") as f:
        parser.readfp(f)
```
With:
```
    parser = configparser.ConfigParser()
    parser.read(setup_cfg)
```

Thx

Exception:
```
2024-01-17 14:48:37.721 ERROR (SyncWorker_3) [homeassistant.util.package] Unable to install package py-smart-gardena==1.3.7: error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /tmp/pip-install-s2wr1lq0/py-smart-gardena_a7e7fb1d2ff34e95874d70b48c6c2294/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-s2wr1lq0/py-smart-gardena_a7e7fb1d2ff34e95874d70b48c6c2294/setup.py", line 16, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-s2wr1lq0/py-smart-gardena_a7e7fb1d2ff34e95874d70b48c6c2294/versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-install-s2wr1lq0/py-smart-gardena_a7e7fb1d2ff34e95874d70b48c6c2294/versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-s2wr1lq0/py-smart-gardena_a7e7fb1d2ff34e95874d70b48c6c2294/versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.


```
Environment: Ubuntu 23.10, Python Virtual Environment

**Comment by ReneNulschDE** [comment]
Hi @grm ,
Do you still maintain this lib? The winter will end in a few weeks and the flowers will need water :-) I can take look on the packaging, but this makes sense only if someone reacts on questions and is reviewing and hopefully approving PRs

**Comment by grm** [comment]
I have upgradeed versionner, it should work now.
Could you give it another try ?

**Comment by ReneNulschDE** [comment]
Thanks for the change.
I have tested:
1. the installation of py-smart-gardena in an fresh 3.12 venv --> Installation without raised exceptions
2. Modified the requirements attribute in the manifest.yaml of the HA-component to `  "requirements": ["git+https://github.com/py-smart-gardena/py-smart-gardena.git@master#py-smart-gardena>1.3.7"]` --> Installation without errors and component is running.

Perfect, thx for your support!
BR
Rene

**Comment by smoki3** [comment]
also looks good here fixes my problem with the integration

https://github.com/py-smart-gardena/hass-gardena-smart-system/issues/192

**Comment by ReneNulschDE** [comment]
thx
