### ISSUE TITLE
Token Validity through websocket

### ISSUE THREAD

**Issue by 0rsa** [py-smart-gardena/py-smart-gardena#28]
Hello,

First, thank you for your work and this library.
I would like to know how many time websocket connection can be handled using the same token?

I'm using it into a Domoticz plugin which never stops.

husqvarnagroup provides an application secret which is for token renewal I guess? Can we imagine token renewal management by the library?

Thank you.

**Comment by grm** [comment]
Hello,

The connection should always be available using the library.
We are using an access token to call all commands and we are using the refresh token when the access token expires. And we should reconnect when the refresh token does not work anymore.

Do you have an issue with connection ?

Regards,
Jérémiee

**Comment by 0rsa** [comment]
I had an issue first day but it works now for 2 weeks ago so I consider token refreshing is working well.
Thank you
