### ISSUE TITLE
Convert to JSON

### ISSUE THREAD

**Issue by Domochip** [py-smart-gardena/py-smart-gardena#66]
Hi, I'm looking for a way to convert device to JSON.
I found out that a good way to do this is to implement a toJSON method.
What's your mind about this?
Do you want me to do a PR about this?

**Comment by grm** [comment]
Hello !

Are you usong this lib in a third party software ? Why using JSON over plain python ?

Jérémie

**Comment by Domochip** [comment]
Hi,

I'm using this lib in my gardena2mqtt docker. ( https://github.com/Domochip/gardena2mqtt )
The objective is to send the whole device through MQTT in JSON format.
I finally did it in my code. However It may be interesting for you.
https://github.com/Domochip/gardena2mqtt/blob/c70a108c37fc0e3b8d0ef0ce8684f0ceec8b6803/gardena2mqtt.py#L10

**Comment by grm** [comment]
Indeed, i have a plan to add a mqtt service for some other integrations !

I'l have a look to your code ! Thanks

Jérémie

**Comment by Domochip** [comment]
I'm running it as a Docker Container :-)
