### ISSUE TITLE
Error from callback

### ISSUE THREAD

**Issue by Pol3cat** [py-smart-gardena/py-smart-gardena#9]
Hi.
sometimes i got this error:
`error from callback <bound method Client.on_close of <gardena.smart_system.Client object at 0x5ecdbdb0>>: (missing_token) Missing access token parameter.`

I started the websocket and a while loop scan every 15seconds the devices for changes in my py-script but the script is still alive and not interrupted.

**Comment by grm** [comment]
Should be fixed with the release made this week end.
When had you this issue ?

**Comment by Pol3cat** [comment]
different times.
today at 8:54 and 12:44:59
before, at 12:44:56 got the error "gardena.smart_system error : ping/pong timed out"

**Comment by grm** [comment]
DOes the integrations still works after ? Or you have to restart home
assistant ?

Regarding the timeout, it can happen with networks, it is not a big deal,
the next ping/pong will pass :)

Grm

**Comment by Pol3cat** [comment]
btw i don't use home assistant. i use SmarthomeNG. ;)
i will update to your current version today. my current is 0.7.3

**Comment by grm** [comment]
And do you have to restart your integration ? Or everything is still working after a disconnection ?

**Comment by Pol3cat** [comment]
i restart my py. And its seams after the error everything is working. Only the error appears ;)

**Comment by Pol3cat** [comment]
i seams that the error is fixed. since two days i have no errors.

**Comment by grm** [comment]
I just corrected an issue in version 0.7.6.
Should be fixed there. Do not hesitate to open a ticket if the issue appears again.
