### ISSUE TITLE
ERROR    404 : {r['errors'][0]['title']} - {r['errors'][0]['detail']}

### ISSUE THREAD

**Issue by Grillfreund** [py-smart-gardena/py-smart-gardena#90]
Hello,

today I would like to try your code for the first time. I would  like to start with your example code from readme.md. But unfortunately I get this error:

`2021-08-15 16:15:38 ERROR    404 : {r['errors'][0]['title']} - {r['errors'][0]['detail']}`

My credentials and client id are correct. Both APIs are connected to my application as described in readme. Do you have any hint for me?

Michael

**Comment by Grillfreund** [comment]
I tested 1h without result. But 1 min after leaving the comment I found the issue by myself. (Username and password was correct; but there was no location connected to it)

**Comment by grm** [comment]
Ha ha ha ! Good to know and have fun with the library !
If you find the documentation not clear on this point, you can totally make
a pr on it ! :)

Jeremie

Le dim. 15 août 2021 à 18:27, Grillfreund ***@***.***> a
écrit :
